23 Спринт
Liocha/PlaylistMaker pull request #16
Opened 2024-08-19 19:15 UTC by Liocha

2024-08-24 09:54 UTC, DmitrijEgorow commented
Пользователь не может вызвать меню с дополнительными возможностями управления плейлистом, если треков в плейлисте много, три точки скрываются за bottom sheet
![Screenshot_20240824_164021_](https://github.com/user-attachments/assets/b35ba8e4-2e45-4679-9385-e67b2663f25b)

2024-08-24 10:01 UTC, DmitrijEgorow commented
- [ ] Если в плейлисте нет добавленных треков, то ❌меню исчезает


https://github.com/user-attachments/assets/f4f6f535-3425-4c8b-affb-30238f3a1c29

2024-08-24 10:10 UTC, DmitrijEgorow requested changes

2024-08-24 10:10 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/media/domain/interactor/impl/PlaylistInteractorImpl.kt
>      override suspend fun saveImageToPrivateStorage(uri: Uri): Uri {
В идеале, чтобы domain слой совсем не зависел от классов Android sdk

2024-08-24 10:10 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/media/ui/EditPlaylistFragment.kt
> +    lateinit var menuBottomSheetBehavior: BottomSheetBehavior<ConstraintLayout>
private ?

2024-08-24 10:10 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/media/ui/EditPlaylistFragment.kt
> +                    putInt("playlistId", it)
Лучше вынести в константу

2024-08-24 10:10 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/media/ui/view_model/CreatePlaylistViewModel.kt
> +    val _description = MutableLiveData("")
Нехорошо, что мы разрешаем снаружи изменять данные в LiveData

2024-08-24 10:10 UTC, DmitrijEgorow commented on app/src/main/res/layout/fragment_edit_playlist.xml
> +            android:id="@+id/imageCover"
Иной стиль именования идентификатора

2024-08-25 15:07 UTC, Liocha commented
> Пользователь не может вызвать меню с дополнительными возможностями управления плейлистом, если треков в плейлисте много, три точки скрываются за bottom sheet ![Screenshot_20240824_164021_](https://private-user-images.githubusercontent.com/36837067/361131925-b35ba8e4-2e45-4679-9385-e67b2663f25b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1ODk3NDEsIm5iZiI6MTcyNDU4OTQ0MSwicGF0aCI6Ii8zNjgzNzA2Ny8zNjExMzE5MjUtYjM1YmE4ZTQtMmU0NS00Njc5LTkzODUtZTY3YjI2NjNmMjViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDEyMzcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmODE4ZTRiNWUxZTFlNzYxZGY1NmQ0NTdhYjcyMmFiNzA0ZjA0NTJlOGZhZDliODk2OGQyZjIxNjZmZDEzZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O8XN1xtWU7k9NbeU--ZuXfVgzzCL_hw1LPGS4H-Z1Fg)

@DmitrijEgorow достаточно ли будет вот в эту область добавить прокрутку? 

![3097](https://github.com/user-attachments/assets/3d90e23c-9a43-415c-b225-17f34c6823e4)

2024-08-27 00:08 UTC, Liocha commented
Поправил основные замечания по ревью.

2024-08-27 17:14 UTC, DmitrijEgorow commented
> > Пользователь не может вызвать меню с дополнительными возможностями управления плейлистом, если треков в плейлисте много, три точки скрываются за bottom sheet ![Screenshot_20240824_164021_](https://private-user-images.githubusercontent.com/36837067/361131925-b35ba8e4-2e45-4679-9385-e67b2663f25b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1ODk3NDEsIm5iZiI6MTcyNDU4OTQ0MSwicGF0aCI6Ii8zNjgzNzA2Ny8zNjExMzE5MjUtYjM1YmE4ZTQtMmU0NS00Njc5LTkzODUtZTY3YjI2NjNmMjViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDEyMzcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmODE4ZTRiNWUxZTFlNzYxZGY1NmQ0NTdhYjcyMmFiNzA0ZjA0NTJlOGZhZDliODk2OGQyZjIxNjZmZDEzZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O8XN1xtWU7k9NbeU--ZuXfVgzzCL_hw1LPGS4H-Z1Fg)
> 
> @DmitrijEgorow достаточно ли будет вот в эту область добавить прокрутку?
> 
> ![3097](https://private-user-images.githubusercontent.com/16827678/361240845-3d90e23c-9a43-415c-b225-17f34c6823e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NzUyNTUsIm5iZiI6MTcyNDc3NDk1NSwicGF0aCI6Ii8xNjgyNzY3OC8zNjEyNDA4NDUtM2Q5MGUyM2MtOWE0My00MTVjLWIyMjUtMTdmMzRjNjgyM2U0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDE2MDkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMzBiMzM3ZmJmMGFiNGIwZDYyYmNiYTI1YzIyNTdkZDQyYjQ1MWZmZTE0ZjkyZjE1ZGIyOWY1MzA2ZmUxNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SKMWqUJBUqwfM51WQ1w3vXzbJRhdXeYowndzq0lQglQ)

Сейчас со скрытием bottom sheet вполне хорошо получилось

2024-08-31 17:10 UTC, merged